### ISSUE TITLE
bundle install on MacOS El Capitan fails due to Event Machine OpenSSL lib

### ISSUE THREAD

**Issue by Dangeranger** [alexch/codelikethis#1]
## Problem

On MacOS El Capitan 10.11.+ and above running `bundle install` will fail due to Apple replacing OpenSSL due to security CVE's.

## Proposed Solution

Change the README to notify users to follow the instructions below to allow EventMachine gem to build using a third party OpenSSL library installed using HomeBrew or other dependency manager.

### Instructions 

1. [Install HomeBrew](https://brew.sh/)
2. Install OpenSSL
`brew install openssl`
3. Install the EventMachine gem v1.0.8 separately with compile flags
```sh
$ gem install eventmachine -- --with-cppflags=-I/usr/local/opt/openssl/include                                                                                                              
Building native extensions with: '--with-cppflags=-I/usr/local/opt/openssl/include'
This could take a while...
Successfully installed eventmachine-1.0.8 1 gem installed
```
4. Alternatively configure bundler to use Brew OpenSSL
```sh
bundle config build.eventmachine --with-cppflags=-I$(brew --prefix openssl)/include
bundle install
```

**Comment by alexch** [comment]
also it seems Ruby 2.5 is not great on Windows yet -- https://rubyinstaller.org/2017/12/25/rubyinstaller-2.5.0-1-released.html  -- "Please note, that many gems are not yet compatible with Ruby-2.5 on Windows. 
You should therefore stay on 2.4.3 until it’s better supported"
